---
- name: start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "public-compute-instance"
    # key_name: "prod-ssh-key"
    # vpc_subnet_id: subnet-5ca1ab1e
    instance_type: t2.micro
    region: ap-south-1
    security_group: default
    state: absent
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secrect_key }}"
    network_interfaces:
      - assign_public_ip: true
    image_id: ami-0d0ad8bb301edb745
    tags:
      Environment: Testing